export const CONFIG = {
  HYBRID_WEIGHT_ALPHA: 0.6,
  POSITIVE_RATING_THRESHOLD: 4.0,
  MIN_SIMILARITY_SCORE: 0.1,
  MIN_PREDICTED_SCORE: 3.0,
  NEIGHBOR_LIMIT: 30,
  CONTENT_CANDIDATE_LIMIT: 500,
  COLLAB_CANDIDATE_LIMIT: 100,
  HYBRID_MERGE_LIMIT: 50,
  DEFAULT_OUTPUT_LIMIT: 10,
  MINIMAL_COMMON_MOVIES: 2,
};

export const SEARCH_CONFIG = {
  DEFAULT_LIMIT: 20,
  DEFAULT_OFFSET: 0,
};
